version: "3.9"

services:
  db-aprend-ia:
    container_name: auth_db
    image: postgres:16.2
    restart: always
    ports:
      - "${DB_PORT_EXT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234567}
      POSTGRES_DB: ${DB_NAME:-authdb}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: