server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: aprendia-api
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234567}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  
  sql:
    init:
      mode: always
      data-locations: 
        - classpath:db/migration/01-basic-data.sql
        - classpath:db/migration/02-learning-paths.sql
        - classpath:db/migration/03-exercises.sql
        - classpath:db/migration/04-impairments.sql
        - classpath:db/migration/05-locations.sql
        - classpath:db/migration/06-persons-initial.sql
        - classpath:db/migration/07-persons-additional.sql
        - classpath:db/migration/14-rol-pariente-data.sql
        - classpath:db/migration/08-students.sql
        - classpath:db/migration/09-institutions.sql
        - classpath:db/migration/10-sequences.sql
        - classpath:db/migration/11-user-table.sql
        - classpath:db/migration/13-usuario-rol.sql
      continue-on-error: false
  
  security:
    jwt:
      secret: aprendia-secret-key-2024
      expiration: 86400000  # 24 horas en milisegundos (24 * 60 * 60 * 1000)

jwt:
  secret: aprendia-secret-key-for-jwt-token-generation-2024
  expiration: 86400000  # 24 horas en milisegundos (24 * 60 * 60 * 1000)

encryption:
  secret: aprendia-encryption-key-2024

app:
  encryption:
    key: aprendia-encryption-key-2024-32x
  cloudinary:
    service-url: ${APP_CLOUDINARY_SERVICE__URL:http://claudinary-image-service:8080/api/cloudinary}

logging:
  level:
    com.icheha.aprendia_api: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true
    filter: true

swagger:
  server:
    url: ${SWAGGER_SERVER_URL:http://localhost:8080}
    production:
      url: ${SWAGGER_PRODUCTION_URL:}